Tweaks to README.md
RSE-Sheffield/fair4rs-lesson-setup pull request #19
Opened 2024-03-29 08:01 UTC by ns-rse

Closes #18

Hopefully addresses most of the minor points noted in #18 and with a bit of luck I won't have messed up the `.patch`.

2024-04-02 13:03 UTC, tdjames1 requested changes
Thanks, Neil, I've suggested a change to the tweak to CONTRIBUTING.md and I spotted another link that could be shortened.

2024-04-02 13:03 UTC, tdjames1 commented on README.md
>    IDE](https://posit.co/download/rstudio-desktop/#download))
```suggestion
- [pandoc][pandoc] (>= 2.11) (available through the [RStudio IDE][rstudio])
```

2024-04-02 13:09 UTC, tdjames1 commented on fair4rs_config.patch
> ++[repo-issues]: https://github.com/<account>/<repo>/issues   <!-- # FIXME -->
Also just noticed the [repo] link has a typo!

```suggestion
+[repo]: https://github.com/<account>/<repo>#FIXME
+[repo-issues]: https://github.com/<account>/<repo>/issues#FIXME
```

2024-04-04 09:32 UTC, ns-rse commented on fair4rs_config.patch
> ++[repo-issues]: https://github.com/<account>/<repo>/issues   <!-- # FIXME -->
Ah, missed that this doesn't render, thanks for correcting and spotting the typo.

2024-04-04 10:20 UTC, tdjames1 requested changes
One more change required to reflect change in the patch to CONTRIBUTING.md.

2024-04-04 10:20 UTC, tdjames1 commented on README.md
> +Update links to GitHub repository and issues, marked `<!-- # FIXME -->`.
```suggestion
Update links to GitHub repository and issues, marked `#FIXME`.
```

2024-04-04 11:05 UTC, ns-rse commented on README.md
> +Update links to GitHub repository and issues, marked `<!-- # FIXME -->`.
Good catch, thanks.

2024-04-04 11:08 UTC, tdjames1 approved these changes
All good, thanks!

2024-04-04 11:55 UTC, merged